labels:
- name: area/bash
  description: ""
  color: cccccc
- name: area/fish
  description: ""
  color: cccccc
- name: area/zsh
  description: ""
  color: cccccc
- name: help wanted
  description: Extra attention is needed
  color: "008672"
- name: kind/bug
  description: Something isn't working
  color: fc2929
- name: kind/enhancement
  description: New feature or request
  color: 84b6eb
- name: kind/question
  description: Further information is requested
  color: cc317c
- name: status/todo
  description: ""
  color: d4c5f9
repos:
- name: b4b4r07/enhancd
  labels:
  - area/bash
  - area/fish
  - area/zsh
  - help wanted
  - kind/bug
  - kind/enhancement
  - kind/question
  - status/todo
