changelog:
  exclude:
    labels:
      - tagpr
  categories:
    - title: Breaking Changes
      labels:
        - kind/breaking-change
    - title: New Features
      labels:
        - kind/feature
    - title: Bug fixes
      labels:
        - kind/bug
    - title: Others
      labels:
        - "*"
