changelog:
  exclude:
    labels:
      - tagpr
      - changelog/skip
  categories:
    - title: Breaking Changes
      labels:
        - kind/breaking-change
    - title: New Features
      labels:
        - kind/feature
    - title: Bug fixes
      labels:
        - kind/bug
    - title: Deprecated features
      labels:
        - kind/deprecation
    - title: Improvements
      labels:
        - kind/improvement
    - title: Refactorings
      labels:
        - kind/cleanup
    - title: Others
      labels:
        - "*"
