.TH enhancd "1" "August 2014" "enhancd v2.1.4" "enhancd Manual"
.
.SH NAME
enhancd \- A simple tool that provides enhanced cd command
.
.
.SH SYNOPSIS
.B
cd [\fI-|..\fP] [\fIDIR\fP]
.
.
.SH DESCRIPTION
\fBenhancd\fP is a next-generation \fBcd\fP command with an interactive filter.

\fBcd\fP command is one of the frequently used commands.

Nevertheless, it is not so easy to handle unfortunately. A directory path given as an argument to \fBcd\fP command must be a valid path that exists and is able to resolve. In other words, you cannot pass a partial path such as "dir" (you are in \fI/home/lisa\fP, dir is \fI/home/lisa/work/dir\fP) to \fBcd\fP command.

The new \fBcd\fP command called "enhancd" enhanced the flexibility and usability for a user. enhancd will memorize all directories visited by a user and use it for the pathname resolution. If the log of enhancd have more than one directory path with the same name, enhancd will pass the candidate directories list to the filter within the ENHANCD_FILTER variable in order to narrow it down to one.

Thanks to that mechanism, the user can intuitively and easily change the directory where you want to go to.
.
.
.SH REQUIREMENTS
\fBenhancd\fP requires more than one interactive filter such as \fIpeco\fP and \fIfzf\fP. You should install it before run enhancd.
.
.IP "peco"
Simplistic interactive filtering tool
.nf
https://github.com/peco/peco
.
.
.SH OPTIONS
.IP "-"
When enhancd takes a hyphen (-) string as an argument, it searchs from the last 10 directory items in the log. With it, you can search easily the directory you used last.

Then, since the current directory will be delete from the candidate, you just press Enter key to return to the previous directory after type \fBcd -\fP (\fB$PWD\fP is /home/lisa, \fB$OLDPWD\fP is /home/lisa/src/github.com/b4b4r07/portfolio).
.
.IP ".."
From the beginning, \fB..\fP means the directory's parent directory, that is, the directory that contains it. When enhancd takes a double-dot (..) string as an argument, it behaves like a \fIzsh-bd\fP plugin. In short, you can jump back to a specific directory, without doing \fBcd ../../..\fP.
.
.
.SH CONFIGURATIONS
.
.IP "\fBENHANCD_DIR\fP"
.
The ENHANCD_DIR variable is a base directory path. It defaults to \fI~/.enhancd\fP.
.
.IP "\fBENHANCD_FILTER\fP"
.
The ENHANCD_FILTER is an environment variable. It looks exactly like the PATH variable containing with many different filters such as peco concatenated using ':'.

Setting the ENHANCD_FILTER variable is exactly like setting the PATH variable. For example:

    $ export ENHANCD_FILTER="/usr/local/bin/peco:fzf:non-existing-filter"

This above command will hold good till the session is closed. In order to make this change permanent, we need to put this command in the appropriate profile file. The ENHANCD_FILTER command in this example is set with 3 components: /usr/local/bin/peco followed by fzf and the not-existing-filter.

enhancd narrows the ENHANCD_FILTER variable down to one. However, the command does not exist can not be the candidate.

Let us try to test this ENHANCD_FILTER variable.

    $ cd

If cd command does not return error, the settings of ENHANCD_FILTER is success.

How to find the value of the ENHANCD_FILTER variable?

    $ echo $ENHANCD_FILTER
    /usr/local/bin/peco:fzf:non-existing-filter
.
.
.SH BUGS
Issue tracking on GitHub:
.nf
https://github.com/b4b4r07/enhancd/issues
.
.
.SH AUTHORS
Created and maintained by BABAROT, with the help oh various contributors:
.nf
https://github.com/b4b4r07/enhancd/graphs/contributors.
.
.
.SH LICENSE
enhancd is licensed under the MIT license.
.nf
https://b4b4r07.mit-license.org
