.TH ENHANCD 1
.SH NAME
.PP
\f[B]enhancd\f[], \f[B]cd\f[] \- Enhancd cd and make your environment useful
.SH SYNOPSIS
.PP
cd [\f[B]-\f[] \f[I]num\f[]] [\f[B]+\f[] \f[I]num\f[]] [\f[B]=\f[] \f[I]num\f[]] [\f[B]-l\f[] | \f[B]--list\f[] \f[I]dir\f[]] [\f[B]-L\f[] | \f[B]--list-detail\f[] \f[I]dir\f[]] [\f[B]--help\f[]] \f[I]directory\f[]
.SH DESCRIPTION
.PP
This tool "enhancd" is a wrapper script of the cd command. Enhancd is being developed based on a script called cdhist.sh, provides a useful function. The directory history is stored to an external file as a database. In addition, the last 10(default) of the history is stored in the directory queue, you can go back or forward on the queue easily.
.PP
On GitHub: <http://github.com/b4b4r07/dotfiles/enhancd>
.PP
.SH OPTIONS
Here is a summary of all the options. The following options are available:
.TP 12
\f[B]-\f[]\ [\f[I]num\f[]]
If count is omitted it defaults to 1.
Go back to the \f[I]num\f[] previous directory.
.br
e.g. 0->1->2->3...
.TP
\f[B]+\f[]\ [\f[I]num\f[]]
If count is omitted it defaults to 1.
Forward to the \f[I]num\f[] previous directory.
.br
e.g. 0->9->8->7...
.TP
\f[B]=\f[]\ [\f[I]num\f[]]
If no arguments are given, show history of directory queue.
When the argument is a numerical value, jump in the number's path that is displayed th side of the directory queue.
.TP
\f[B]-l\f[]\ [\f[I]dir\f[]],\ \f[B]--list\f[]\ [\f[I]dir\f[]]
In this \f[B]-t\f[] option, show only histories registered in the enhancd database as complement candidates.
In other words, it does not display a directory that exists in the current working directory as complement candidates. If no arguments are given, show all directory histories.
.TP
\f[B]-L\f[]\ \f[I]dir\f[],\ \f[B]--list-detail\f[]\ \f[I]dir\f[]
The \f[B]-l\f[] option, it displays as a candidate to complement the only head name of the directory path. On the other hand, display the head name and the full path as its description in the \f[B]-L\f[] option.
.TP
.BI --help
Print  (on  the standard output) a description of the command line options understood by enhancd.
.SH ENVIRONMENT
.TP 12
ENHANCD_DATABASE
Location to save the text file that is being used as the enhancd database of movement history.
.TP
ENHANCD_CDHOME
Directory path that is treated as $HOME in this script.
If no argument is given, change the current directory to ENHANCD_CDHOME.
.TP
ENHANCD_DISP_QUEUE
When you change the working directory by using 'cd -' or 'cd +', whether or not to display the directory queue stats.
.TP
ENHANCD_AUTOADD
test test test test test test test test test test test test test test test
Automatically, add some information of paths to the enhancd database.
These are written to the database beginning, not at all the end of the database.

First, add all of the hierarchy of the directory of full path of to the enhancd database.

  example:
      $ cd /path/to/hoge/etc

      * Add  /path
      * Add  /path/to
      * Add  /path/to/hoge
        NOT  /path/to/hoge/etc

Secondly, add depth 1 of the directory directly under the moved directory to the enhancd database.

  example:
      $ cd /path/to/hoge/etc

      * Add  /path/to/hoge/etc/dir_a
      * Add  /path/to/hoge/etc/dir_b
        NOT  /path/to/hoge/etc/dir_b/dir_c
.TP
ENHANCD_REFRESH_STARTUP
Whether delete or not all the directory that does not exist from the enhancd database at startup of enhancd script.
.TP
ENHANCD_HOME_STARTUP
Whether `cd $HOME` or not at startup of enhancd script.
.TP
ENHANCD_CDQMAX
The maximum number of directory queue that is used in the 'cd -/+/=' command.
It is hard to see if you specify a number greater in this variable.
Therefore we do not recommend.
.TP
ENHANCD_COMP_LIMIT
When the tab completion of the cd command, limits the candidates of the history of displaying the complement from the enhancd database.
  Note: If you specify a large number, there is a case in which the screen is
        filled.
Use the -l option if you want to tab complement all of history as a candidate.
.TP
ENHANCD_PECO_BIND
Define the key binding to run the interactive complement by peco/peco.
.SH LICENSE
MIT License
.SH AUTHORS
B4B4R07 <b4b4r07@gmail.com>.
