# Sync labels with the definition YAML

name: Sync labels
on:
  push:
    branches:
    - master
    - main
    paths:
    - .github/labels.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: micnncim/action-label-syncer@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        manifest: .github/labels.yaml
